package ru.tsconsulting.errorHandling;

public enum Errors {
	DEPARTMENT_NOT_EMPTY, ATTRIBUTE_NOT_SPECIFIED, DEPARTMENT_HAS_SUB_DEPARTMENTS, ENTITY_NOT_FOUND, PARSE_FAIL,
	INVALID_HIERARCHY, ALREADY_EXISTS, ALREADY_FIRED, ALREADY_HIRED, INVALID_ATTRIBUTE
}
