INSERT INTO TEST_B.DEPARTMENT (ID, IS_DISMISSED, NAME) VALUES (DEPARTMENT_SEQUENCE.nextval,0,'ADMIN');
INSERT INTO TEST_B.EMPLOYEE_REVINFO(ID, TIMESTAMP) VALUES (EMPLOYEE_REV_SEQUENCE.nextval,1505896965404);
INSERT INTO TEST_B.DEPARTMENT_AUD(ID, REV, REVTYPE, IS_DISMISSED, NAME) VALUES (DEPARTMENT_SEQUENCE.currval, 1, 0, 0, 'ADMIN');
INSERT INTO TEST_B.EMPLOYEE (ID, IS_FIRED, PASSWORD, USERNAME, FIRSTNAME, LASTNAME, DEPARTMENT_ID) VALUES (EMPLOYEE_SEQUENCE.nextval, 0, '$2a$06$wZqzsXQFiu5Z21bezTnGWOQg55AH1ojWp6XeQ.050zLjevfElm3Yy', 'admin', 'JON', 'SAND', 1);
INSERT INTO TEST_B.EMPLOYEE_AUD (ID, REV, REVTYPE, IS_FIRED, PASSWORD, USERNAME, FIRSTNAME, LASTNAME, DEPARTMENT_ID) VALUES (EMPLOYEE_SEQUENCE.currval,1,0,0,'$2a$06$wZqzsXQFiu5Z21bezTnGWOQg55AH1ojWp6XeQ.050zLjevfElm3Yy','admin','JON','SAND',1);
INSERT INTO TEST_B.ROLES_LIST (ROLE_ID, EMPLOYEE_ID) VALUES ('ROLE_ADMIN', 1);
INSERT INTO TEST_B.ROLES_LIST (ROLE_ID, EMPLOYEE_ID) VALUES ('ROLE_USER', 1);
INSERT INTO TEST_B.ROLES_LIST (ROLE_ID, EMPLOYEE_ID) VALUES ('ROLE_EDITOR', 1);
