INSERT INTO TEST_B.USERS (ID, ENABLED, PASSWORD, USERNAME) VALUES (1, 1, '$2a$06$wZqzsXQFiu5Z21bezTnGWOQg55AH1ojWp6XeQ.050zLjevfElm3Yy', 'admin');
INSERT INTO TEST_B.ROLES_LIST (ROLE_ID, USER_ID) VALUES (1, 1);
INSERT INTO TEST_B.ROLES_LIST (ROLE_ID, USER_ID) VALUES (2, 1);
INSERT INTO TEST_B.ROLES_LIST (ROLE_ID, USER_ID) VALUES (3, 1);
