//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 02:51:56 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tsconsulting.ru/employee-ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.tsconsulting.employee_ws;
